import Peer from "peerjs"
import { useEffect, useState } from "react"

export const Create: React.FC = () => {

    const [data, setData] = useState<any[]>([])

    useEffect(() => {
        // Create peer instance for host
        const peer = new Peer('your-peer-id-can-be-autogenerated-as-well-however-must-be-the-same-at-connect')

        // Log id
        peer.on('open', () => {
            console.log('ID: ' + peer.id)
        })

        // Wait till you get a connection. Data will be the sent data.
        peer.on('connection', (conn) => {
            conn.on('data', (data) => {

                // Print sent data
                console.log(data)
                setData(value => [...value, data])
            })
        })

    }, [])
    return <>
        <h2>Create</h2>

        <p>Recieved data:</p>
        {data.map(item => <p>{item}</p>)}
    </>
}