import Peer from "peerjs"
import { useEffect, useState } from "react"

export const Create: React.FC = () => {

    const [data, setData] = useState<any[]>([])
    const [connection, setConnection] = useState<any[]>([])
    useEffect(() => {
        // Create peer instance for host
        const peer = new Peer('your-peer-id-can-be-autogenerated-as-well-however-must-be-the-same-at-connect')

        // Log id
        peer.on('open', () => {
            console.log('ID: ' + peer.id)
        })

        // Wait till you get a connection. Data will be the sent data.
        peer.on('connection', (conn) => {
            setConnection(value => [...value, conn.connectionId])
            conn.on('data', (data) => {

                // Print sent data
                console.log(data)
                setData(value => [...value, data])
            })

            conn.on('close', () => {
                setConnection(value => value.filter(id => conn.connectionId !== id))
            })
        })

    }, [])
    return <>
        <h2>Create Lobby</h2>

        <h3>Connected</h3>
        {connection.map(item => <p>{item}</p>)}

        <h3>Recieved data:</h3>
        {data.map(item => <p>{item}</p>)}
    </>
}