import Peer from "peerjs"
import { useEffect } from "react"

export const Join: React.FC = () => {
    useEffect(() => {
        // Create peer instance to connect
        const peer = new Peer()

        peer.on('open', () => {

            // When ready build connection
            const conn = peer.connect('your-peer-id-can-be-autogenerated-as-well-however-must-be-the-same-at-connect')

            // When ready send hi. Host will recieve hi!
            conn.on('open', () => {
                conn.send('hi!')
            })
        })
    }, [])
    return <>
        <h2>Join</h2>
    </>
}